### PR TITLE
Well, at first I made some changes in the front-end design (color change, adding up the fedora logo, change the position of the source link, white background tabs with collapse). How about adding a new link to the fedora badges? 

### PR DESCRIPTION
**Pull request by lobovit**

### CODE REVIEW

**Comment by pypingou** [comment]
Could you maybe provide a little more information as to what each commit is doing? The commit message are rather unclear.

**Comment by lobovit** [comment]
Alright. I don't informed because the github somehow already tells you what
the changes were. But ok, I'll send commits with better comments.

2014-06-29 5:15 GMT-03:00 Pierre-Yves Chibon notifications@github.com:

**Comment by pypingou** [comment]
Github is a plateform on the top of git, the tool that matters is git, not github.

In addition, if even git can show you the changes but it does not provide any explanation as to why these changes were made.

**Comment by lobovit** [comment]
Ok, sorry :)

2014-06-30 9:48 GMT-03:00 Pierre-Yves Chibon notifications@github.com:

**Comment by pypingou** [comment]
No problem ;-)

And it's always nice to see new people interesting in this small application :)

**Comment by lobovit** [comment]
Well, at first I made some changes in the front-end design (color change,
adding up the fedora logo, change the position of the source link, white
background tabs with collapse). How about adding a new link to the fedora
badges?

2014-06-30 10:22 GMT-03:00 Pierre-Yves Chibon notifications@github.com:

**Comment by lobovit** [comment]
This small application will be very useful for ambassadors fedora and
members of the team in general. Or even to implement the feature on news
portals (there is a proposal to re opening fedora magazine in Brazil for
example).

2014-06-30 10:23 GMT-03:00 Vitor Lobo lobocode@gmail.com:

**Comment by pypingou** [comment]
I fear I have probably not be clear, I was speaking about improving the commit messages so that the information is and remains present for all

**Comment by pypingou** [comment]
ping? Need some help to fix the commit messages?

**Comment by pypingou** [comment]
ping ?

**Comment by lobovit** [comment]
At home, I'm revamping the entire front-end of fedora news using bootstrap metroui and separating html modules each link (easier to support in this way). Soon I will show this experiment :)

**Comment by pypingou** [comment]
How does bootstrap metroui behaves on mobiles?

**Comment by lobovit** [comment]
Very well.Is responsive and ideal for this project.

**Comment by pypingou** [comment]
I'm going to close this for now.

Please open a new pull-request when you have your work ready and please be careful with the commit messages :)

Thanks for your work!

**Pull request closed without merging**
